# Generated by Django 5.1.7 on 2025-04-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('resource_id', models.CharField(max_length=255)),
                ('channel_token', models.CharField(max_length=255)),
                ('last_page_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMeetTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('generated', 'Generated'), ('missing', 'Missing'), ('failed', 'Failed')], default='missing', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('is_vector_stored', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'file_id'], name='input_data__user_id_8d8edc_idx'), models.Index(fields=['status'], name='input_data__status_f8f8b8_idx'), models.Index(fields=['created_time'], name='input_data__created_1c20bd_idx')],
                'unique_together': {('user', 'file_id')},
            },
        ),
        migrations.CreateModel(
            name='YouTubeTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('is_vector_stored', models.BooleanField(default=False)),
                ('channel_url', models.URLField(blank=True, null=True)),
                ('processed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'video_id'], name='input_data__user_id_ee53bf_idx'), models.Index(fields=['status'], name='input_data__status_098fe2_idx'), models.Index(fields=['created_at'], name='input_data__created_049512_idx')],
                'unique_together': {('user', 'video_id')},
            },
        ),
        migrations.CreateModel(
            name='ZoomTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('meeting_id', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('generated', 'Generated'), ('missing', 'Missing')], default='missing', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_vector_stored', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'file_id'], name='input_data__user_id_22ccdc_idx'), models.Index(fields=['status'], name='input_data__status_4800ae_idx'), models.Index(fields=['start_time'], name='input_data__start_t_60a6c8_idx')],
                'unique_together': {('user', 'file_id')},
            },
        ),
    ]
