# Generated by Django 5.1.7 on 2025-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstoken',
            name='access_token',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='teamstoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
